name: Deploy Image to Production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build --build-arg VITE_MODE=production -t fsngpz/acr-backoffice-prod-image:latest .

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: |
          docker push fsngpz/acr-backoffice-prod-image:latest
  deploy:
    name: Deploy to production
    runs-on: [ backoffice-acr-ec2-prod ]
    needs: build
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull fsngpz/acr-backoffice-prod-image:latest
      - name: Delete previous docker container
        run: sudo docker rm -f acr-website
      - name: Run docker container
        run: sudo docker run -d -p 80:80 --name acr-website fsngpz/acr-backoffice-prod-image:latest
