name: Docker CI/CD

on:
  push:
    branches:
      - master # Run on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build --build-arg VITE_MODE=development -t fsngpz/acr-backoffice-dev-image:latest .

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: |
          docker push fsngpz/acr-backoffice-dev-image:latest
  deploy:
    name: Deploy to development
    needs: build
    runs-on: [ backoffice-acr-ec2-dev ]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull fsngpz/acr-backoffice-dev-image:latest
      - name: Delete previous docker container
        run: sudo docker rm -f acr-backoffice
      - name: Run docker container
        run: sudo docker run -d -p 80:80 --name acr-backoffice -e NODE_ENV=development fsngpz/acr-backoffice-dev-image:latest
